// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAgIE15XkPSjTPJD3CiFX1tNoJti9Iz_-M',
    appId: '1:401829163969:web:72cbcd33ee95bdb5e47540',
    messagingSenderId: '401829163969',
    projectId: 'purangy-3e896',
    authDomain: 'purangy-3e896.firebaseapp.com',
    storageBucket: 'purangy-3e896.appspot.com',
    measurementId: 'G-PTMLP90707',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAuBJlbsypGdMjnfRzlpKPGpNqu5qvL09Y',
    appId: '1:401829163969:android:4b4e502f6e16d66ae47540',
    messagingSenderId: '401829163969',
    projectId: 'purangy-3e896',
    storageBucket: 'purangy-3e896.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB-kokVjOdy1xV2n4a5ZaLWDwvj3D--K2M',
    appId: '1:401829163969:ios:46f5b649ecfcc9b5e47540',
    messagingSenderId: '401829163969',
    projectId: 'purangy-3e896',
    storageBucket: 'purangy-3e896.appspot.com',
    iosBundleId: 'com.example.purangy',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB-kokVjOdy1xV2n4a5ZaLWDwvj3D--K2M',
    appId: '1:401829163969:ios:432f2a277c358e7ae47540',
    messagingSenderId: '401829163969',
    projectId: 'purangy-3e896',
    storageBucket: 'purangy-3e896.appspot.com',
    iosBundleId: 'com.example.purangy.RunnerTests',
  );
}
